### ISSUE TITLE
Transfer repo to Cake.Contrib org

### ISSUE THREAD

**Issue by pitermarx** [pitermarx/Cake.JMeter#13]
@Roemer any issues with that?
@gep13 if there is no response here i'll transfer it

**Comment by gep13** [comment]
@pitermarx sounds like a plan. As I mentioned on Twitter, I can add @Roemer to the Cake-Contrib Organisation as well, with full access rights to the repository, in the same way that they might have here under your repository.

**Comment by Roemer** [comment]
Fine for me.

**Comment by gep13** [comment]
@pitermarx @Roemer this has now been completed.

@Roemer I have invited you to join the Cake-Contrib Organisation, with admin rights to this repository.  Do you have a Twitter account, and an email that I can use to invite you to a Slack Team?  These are two mechanisms that we use to keep in touch with addin maintainers.

Thanks
